FROM node:22.20-bookworm-slim AS builder

RUN corepack enable && corepack prepare pnpm@10.6.1 --activate

WORKDIR /app
COPY . /app

RUN pnpm install --frozen-lockfile
RUN pnpm --filter ./apps/frontend run build

FROM node:22.20-bookworm-slim AS runner

ENV NODE_ENV=production
ENV HOSTNAME=0.0.0.0
ENV PORT=4200

RUN corepack enable && corepack prepare pnpm@10.6.1 --activate

WORKDIR /app

COPY --from=builder /app/apps/frontend/public ./apps/frontend/public
COPY --from=builder /app/apps/frontend/.next/standalone ./apps/frontend/.next/standalone
COPY --from=builder /app/apps/frontend/.next/static ./apps/frontend/.next/static
COPY --from=builder /app/node_modules/next/node_modules/@swc/helpers ./apps/frontend/.next/standalone/node_modules/next/node_modules/@swc/helpers
COPY var/docker/frontend.standalone.package.json ./apps/frontend/package.json
COPY var/docker/railway-cd-entrypoint.sh /usr/local/bin/cd
RUN chmod +x /usr/local/bin/cd

CMD ["node", "apps/frontend/.next/standalone/apps/frontend/server.js"]
