ARG RAILWAY_SERVICE_NAME=postiz-app

FROM node:22.20-bookworm-slim AS builder
ARG NEXT_PUBLIC_VERSION
ENV NEXT_PUBLIC_VERSION=$NEXT_PUBLIC_VERSION
RUN apt-get update && apt-get install -y --no-install-recommends \
    g++ \
    make \
    python3-pip \
    bash \
&& rm -rf /var/lib/apt/lists/*
RUN npm --no-update-notifier --no-fund --global install pnpm@10.6.1 pm2

WORKDIR /app

COPY . /app

RUN pnpm install
RUN NODE_OPTIONS="--max-old-space-size=4096" pnpm run build

FROM node:22.20-bookworm-slim AS postiz-app

RUN apt-get update && apt-get install -y --no-install-recommends nginx \
 && rm -rf /var/lib/apt/lists/* \
 && addgroup --system www \
 && adduser --system --ingroup www --home /www --shell /usr/sbin/nologin www \
 && mkdir -p /www \
 && chown -R www:www /www /var/lib/nginx \
 && npm --no-update-notifier --no-fund --global install pnpm@10.6.1 pm2

WORKDIR /app

COPY --from=builder /app /app
COPY var/docker/nginx.conf /etc/nginx/nginx.conf

CMD ["sh", "-c", "nginx && pnpm run pm2"]

FROM node:22.20-bookworm-slim AS postiz-frontend

ENV NODE_ENV=production
ENV HOSTNAME=0.0.0.0
ENV PORT=4200

RUN corepack enable && corepack prepare pnpm@10.6.1 --activate

WORKDIR /app

COPY --from=builder /app/apps/frontend/public ./apps/frontend/public
COPY --from=builder /app/apps/frontend/.next/standalone ./apps/frontend/.next/standalone
COPY --from=builder /app/apps/frontend/.next/static ./apps/frontend/.next/static
COPY --from=builder /app/node_modules/next/node_modules/@swc/helpers ./apps/frontend/.next/standalone/node_modules/next/node_modules/@swc/helpers
COPY var/docker/frontend.standalone.package.json ./apps/frontend/package.json
COPY var/docker/railway-cd-entrypoint.sh /usr/local/bin/cd
RUN chmod +x /usr/local/bin/cd

CMD ["node", "apps/frontend/.next/standalone/apps/frontend/server.js"]

FROM ${RAILWAY_SERVICE_NAME} AS final
